//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoaHoc.DbConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoAnTotNghiep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoAnTotNghiep()
        {
            this.SinhVien_DoAnTotNghiep = new HashSet<SinhVien_DoAnTotNghiep>();
        }
    
        public int Id { get; set; }
        public string MaDeTai { get; set; }
        public string TenDeTai { get; set; }
        public System.DateTime ThoiGianDanKy { get; set; }
        public string MoTa { get; set; }
        public string FileDinhKem { get; set; }
        public string GhiChu { get; set; }
        public int GiangVienHuongDanId { get; set; }
        public bool TrangThai { get; set; }
        public int NamHoc { get; set; }
        public int HocKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_DoAnTotNghiep> SinhVien_DoAnTotNghiep { get; set; }
    }
}
