//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoaHoc.DbConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiNghiKhoaHoc
    {
        public int Id { get; set; }
        public string MaBaiBao { get; set; }
        public string TenBaiBao { get; set; }
        public int NguoiSoHuuId { get; set; }
        public int TrangThai { get; set; }
        public Nullable<int> ThoGianDangBai { get; set; }
        public string MoTa { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
