//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoaHoc.DbConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien_DoAnTotNghiep
    {
        public int Id { get; set; }
        public int DoAnTotNghiepId { get; set; }
        public int SinhVienId { get; set; }
    
        public virtual DoAnTotNghiep DoAnTotNghiep { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
