//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoaHoc.DbConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.SinhVien_DoAnTotNghiep = new HashSet<SinhVien_DoAnTotNghiep>();
            this.SinhVien_HKSV = new HashSet<SinhVien_HKSV>();
        }
    
        public int Id { get; set; }
        public int TaiKhoanId { get; set; }
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public string BoMon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_DoAnTotNghiep> SinhVien_DoAnTotNghiep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien_HKSV> SinhVien_HKSV { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
